version: '3.8'

services:
  api:
    restart: always
    image: anthonybronca/firebnb-api:latest
    build:
      context: .
      target: api
    ports:
      - "80:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    #   - .env
