version: '3.8'
services:
  web:
    build: .
    env_file: .env
    depends_on:
      - migration
    ports:
      - 8000:8000

  migration:
    build:
      context: .
      target: production
    env_file: .env
    command: ["sh", -c, "npm run build && npm start"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    restart: always
    user: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      # Might want to adjust depending on your system
      test: [ "CMD", "pg_isready" ]
      interval: 0.5s
      timeout: 5s
      retries: 50

volumes:
  db-data:
