version: '3.8'

services:
  app:
    restart: always
    image: anthonybronca/firebnb:latest
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}

    #   - .env
