version: '3.4'

services:
  api:
    build:
      context: .
      target: production
    # volumes:
    #   - ./:usr/src/var/www/app
    #   - /usr/src/var/www/node_modules
    ports:
      - 80:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
