
const fakeDescriptions = [
"This house is a lakefront paradise with a private pool, Paddleboards, Kayaks, a Game room, a King bed in the Master, 70 inch TV, Fast WIFI, Coffee Bar with espresso and cappuccino, body jets and rain head in the shower, 16-foot kitchen island, 42-inch cabinets, travertine floors, gorgeous granite counters, 7 miles to the airport, 5 miles to Downtown Orlando, 20 miles to Disney, 14 miles to Universal, 55 miles to Cocoa Beach. 14 miles to the convention center.",
"This studio apartment is located in the lower level of our home and is perfect for one or two people. It has a private entrance, a king bed, overlooks the pool and the lake with views of downtown Orlando. Please note there is no kitchen, but there is a wetbar with microwave and mini fridge. In addition to the indoor shower, there is also a outdoor shower and a dock with canoe. Please also note the inside ceiling height is lower than average at 6'3”.",
"The Gecko Unit is located on the downstairs South side of our building with spectacular views of the Atlantic Ocean! Centrally located we are walking distance to Flagler Avenue which is a popular destination that offers shops, restaurants, bars and boutiques. Also close to Publix & Walgreens, everything at your fingertips! We are stocked with everything you need to enjoy a relaxing day on the beach and take in the eclectic vibes that New Smyrna Beach has to offer! Pet friendly too!",
"beautiful residence with 2 Bed - 2.5Bath with a breathtaking salt pool overlooking Lake Sumner / Newly constructed architectural unique space. Sleep 4 people / Easy parking / Private helipad for guests coming by air 🚁 NO PETS ALLOWED",
"Live your fairytale vacation at this stylish, family friendly vacation home. Play and relax in your private pool and hot tub on a peaceful and secluded corner with a lake view. The kids will always remember their favorite characters life-size on their own bedroom walls, and Avengers VR video game motorcycle! No fighting over toilets and showers with FIVE bathrooms! Feel right at home with a full-size kitchen, indoor and outdoor dining, and living room. Write vacation memories to last a lifetime.",
"Welcome to your family’s beach paradise! Sea View Play is one of New Smyrna Beach’s premiere luxury homes located right across from the ocean waves. In addition to its 5-bedroom, 5.5-bathroom layout, this 3-story home is a quick walk to the beach and local restaurants. From a first-floor suite to a crow’s nest with amazing views, your group of 12 will be never forget this luxe beach experience.",
"Newly renovated, 1 KING/ 2 BATH/ 1BALCONY condo for an ideal getaway. Condo located within 10 min. from Disney property, 15 min. for Universal, 25 min. to Downtown Orlando, and 1 hr. to the beach. From the 12th floor unit, you can enjoy the sunrise over Lake Bryan in the morning. Yep, that's right - your view is SKY HIGH, the best in Central Florida. Parking included in price and there are NO ADDITIONAL RESORT FEES.",
"Minutes from Disney, stylish & modern 2bed/2bath fully equipped apartment for up to 6 guests, located in the family friendly Storey Lake Resort. Enjoy our pond view from the balcony.Master suite has a King bed & 55 inch TV. Second bedroom has a Queen bed & a Twin bunk bed. The open floor plan blends Kitchen, Dining and Living room. Close to outlet malls & retail stores.Great amenities: Pools, Kids Splash Zone, Water Slides, Lazy River, Gym, Mini Golf, Kayak, Tiki Bar & Ice Cream Shop.",
"Sunset Lakes is a gated community on the west side of Walt Disney World just a few moments drive from the ‘192’ with its abundant eateries and shops including outlet stores. It is located in Kissimmee. Kissimmee is a city in central Florida's Osceola County, just south of Orlando. It’s defined by its proximity to the region’s multitude of amusement parks, including the massive Walt Disney World Resort complex. Find world-famous attractions just minutes away at Walt Disney World, Universal Orlando and SeaWorld Orlando. Continue the adventure with a zipline ride through the treetops, or soar above it all on a hot air balloon ride.",
"★GORGEOUS★ 2 bedroom apt in new luxury community Storey Lake. The unit has a master bedroom with a king bed and an en-suite bathroom, and a second bedroom with a full bed with twin bunk bed. Also, we have a single sofa bed and Full size Murphy bed just in case that you need it. Washer and dryer on suite. Fully equipped Kitchen. On suite Security box.",
"Enjoy waterpark, kayak rentals and mini golf. Only 5 miles away from Disney and 3 miles away from the Orlando Premium Outlets * ",
"Located directly on N Beach in New Smyrna Beach FL, this 2 BR/2 BA condo has prime ocean views which scream paradise! Just steps to the beach, this small complex also offers a heated pool, charcoal grills, and a short walk to popular Flagler Ave, where there is no shortage of restaurants & bars w/ live music, shopping. NSB is the place to be!",
"A quiet beach townhome a few feet from the beach. The home has wifi and cable channels. The private beach area is away from the public beaches so you enjoy peace and quiet. This is not a stripped down rental unit. We have a strict no pet policy. Please note that in between rentals, some item may not be available or can be lost, stolen or damaged. We may not be able to provide all the amenities as described. Thank you!",
"Luxurious furnishings and more space than you could ever want wait for you in the Lakeview Executive Penthouse condo at Vista Cay Resort. Your Florida vacation will be complete when you step into the elegantly decorated living area, full of plush leather furniture and lots of room to unwind. Right outside the large living area is a breathtaking patio balcony with a stunning view of Lake Cay and plenty of seating for sunset cocktails.",
"LIVE LIKE A LOCAL. Unwind in our stylish city views apartment, centrally-located in the heart of Orlando Central Business District. A convenient stay for work or just a night out in Downtown. This bright lil' slice of heaven has all the luxury essentials you need and is in close proximity to so many great restaurants, venues and bars.",
"Luxury 4 bedrooms pool home with clubhouse",
"Amazing view of Hollywood from rooftop and walking distance to walk of fame and many attractions. Unit is fully equipped with all essentials and everything you need. Beverly Hills, Universal Studio within 5 mile radius and open space kitchen with Central AC/Heating.",
"Park the cars in the private 2-space garage with gate access, then head up to this bright and open property. Watch Netflix and live cable via YouTube TV in your private room with en-suite bathroom. Later, spend time in the open concept living and dining area for some meaningful connection time.Park the cars in the private 2-space garage with gate access, then head up to this bright and open property. Watch Netflix and live cable via YouTube TV in your private room with en-suite bathroom. Later, spend time in the open concept living and dining area for some meaningful connection time.",
"Welcome to our luxury home located near downtown LA! A true 4 bedroom home, it is perfect for families/friends traveling together. Within minutes to all major attractions. or Stay home and enjoy the magical open-air rooftop deck.",
"Serene retreat, nestled in the Hollywood Hills; spiritual zen, private oasis. Sensuous & cool with a modern Asian/Balinese influence, perfect for indoor/outdoor entertaining. Every bathroom offers peace & relaxation. Spacious master bedroom with fireplace and en-suite bathroom, soaking tub, and rain shower. Lounge in the outdoor heated spa. This home evokes an emotional response. Also, we are pet friendly.",
"💙 Absolutely stunning ONE OF A KIND brand new home! This house was completely remodeled from the ground up by a professional interior designer with the focus of comfort, elegance, space and design.",
 "Great place to stay when you want to get away from it all",
"The place to be. One night at a time",
"Developers paradise",
"Nessi's favorite lounge",
"Home of the Giants, a few feet away",
"See dolphins from your balcony, the ocean breeze at night, and mimosas in the morning",
"Teams of developers make big company moves here",
"This is the place to be all the time",
"Suburban home tucked away from the city",
'Suburban home right next to the city',
"Suburban home somehow inside the city",
"City home but not in the city",
"Rural home that is on the edge of surbubia",
"Disney getaway home for your family and friends",
"Pine watch home with palm tree views",
"Coral Drive is just a stone throw away",
"This is where dreams are made of",
"The nights will have fireflies, and the day will have sunkissed sun rays",
"Golden hour never looked so golden! Stay at the most golden place of all!",
"Willy Wonka's factory is just right around the corner",
"Did you know you can click the about links at the bottom to see the info of our dev team?",
"This website was built entirely with Typescript! Really!",
"We used docker to deploy this",
"Mirage Voyage flies above!",
"Wattson's pylon is right next door",
"Crypto Dish sometimes scans this place, but it is a great place to be!",
"This place has the high ground",
"The avengers can be seen fighting aliens from your gorgeous kitchen at this retreat. Beware of aliens.",
"This home belongs to someone that was snapped away by Thanos. Enjoy your stay!",
"The owner of this home doesn't know I listed their house for Firebnb. Lol!",
"If you stay here, you must bring pizza!"
]


export default fakeDescriptions
