const random = require('getrandomjs')

interface Spot {
    userId: number,
    name: string,
    address: string,
    city: string,
    state: string,
    country: string,
    description: string,
    price: number,
    lat: number,
    lng: number,
}


const propertNames = [
    "Cozy 4 Bedroom",
    "3 bed 3 bath",
    "Nightly Cottage",
    "Beautiful Luxuary mansion",
    "Lake views",
    "Lake and pool views",
    "Beach views",
    "Beach and ocean views",
    "Fort-Lauderdale Beach",
    "Beach Place views",
    "Mountain views",
    "Downtown home",
    "Quiet suburban retreat",
    "Quiet rural retreat",
    "Home away from home",
    "Timeshare condo",
    "Palm Tree stay",
    "World's Most Famous Beach House",
    "Cocoa Beach",
    "Satellite Beach",
    "Disney Firework views",
    "Hawaiian retreat",
    "Surfside house",
    "Hike Trail home",
    "European-style home",
    "Japanese-style home",
    "Savanna-style home",
    "Southern-style home",
    "American-dream home",
    "Great Outdoors home",
    "Beach home",
    "Kid-free resort",
    "Personal resort",
    "Vacation resort",
    "Small family-friendly house",
    "Central Florida getaway",
    "Colorado getaway",
    "Maui getaway",
    "Mexican-style home",
    "Mexican retreat",
    "Cuban-style home",
    "Cuban retreat",
    "German-style home",
    "German retreat",
    "Cozy German Cottage",
    "Irish-style home",
    "Irish-style cottage",
    "Irish getaway",
    "Italian springs home",
    "Italian getaway",
    "Canal view",
    "Laid-back home",
    "Corporate retreat home",
    "Finance St. View",
    "Wall St. on Elms St. View"
];
const fakeAddresses = [
    "71963 Schiller Isle",
    "7536 Johnson Mall",
    "37312 Elenora Pines",
    "42158 Aileen River",
    "919 Kutch Underpass",
    "2207 Abbott Streets",
    "5159 Jana Park",
    "85910 Haley Camp",
    "39295 Wolf Meadow",
    "369 Gusikowski Valley",
    "688 Bradtke Isle",
    "21576 Bauch River",
    "8965 Blanche Plaza",
    "80222 Hand Trail",
    "98898 Berta Mills",
    "1839 Murphy Junction",
    "702 Upton Overpass",
    "71720 Laron Plains"
];
const fakeCities = [
    "Orlando",
    "Lake Erica",
    "Koelpinstead",
    "Redondo Beach",
    "Pearl City",
    "Bikini Bottom",
    "Tremblayberg",
    "Nessi",
    "Sparks",
    "Boylefurt",
    "Frankfurt",
    "New York",
    "Los Angles",
    "Port Arturo",
    "Moenbury",
    "Loweville",
    "Louis Ville",
    "Boulder",
    "Maui",
    "Miami",
    "Fort-Lauderdale",
    "Lake Maraside",
    "Pitsburgh",
    "Fort Ellie",
    "Fort Drum",
    "Madrid",
    "Barcelona",
    "Porto",
    "Manchester",
    "Liverpool",
    "Tokyo",
    "Leaf Village",
    "Kawasaki",
    "Mexico City",
    "Dublin",
    "London",
    "San Francisco",
    "Rino",
    "Springfield",
    "Chicago",
    "Tampa",
    "Cocoa Beach",
    "Daytona",
];
const fakeStates = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
];
const fakeDescriptions = [
    "Rerum quidem corrupti reiciendis sapiente cum. Neque sequi tempore cum.",
    "Nesciunt quos architecto est animi beatae sapiente mollitia.",
    "Voluptatem corporis debitis quasi sunt nesciunt rem eveniet.",
    "Great place to stay when you want to get away from it all",
    "The place to be. One night at a time",
    "Developers paradise",
    "Nessi's favorite lounge",
    "Home of the Giants, a few feet away",
    "See dolphins from your balcony, the ocean breeze at night, and mimosas in the morning",
    "Teams of developers make big company moves here",
    "This is the place to be all the time",
    "Suburban home tucked away from the city",
    'Suburban home right next to the city',
    "Suburban home somehow inside the city",
    "City home but not in the city",
    "Rural home that is on the edge of surbubia",
    "Disney getaway home for your family and friends",
    "Pine watch home with palm tree views",
    "Coral Drive is just a stone throw away",
    "This is where dreams are made of",
    "The nights will have fireflies, and the day will have sunkissed sun rays",
    "Golden hour never looked so golden! Stay at the most golden place of all!",
    "Willy Wonka's factory is just right around the corner",
    "Did you know you can click the about links at the bottom to see the info of our dev team?",
    "This website was built entirely with Typescript! Really!",
    "We used docker to deploy this",
    "Mirage Voyage flies above!",
    "Wattson's pylon is right next door",
    "Crypto Dish sometimes scans this place, but it is a great place to be!",
    "This place has the high ground",
    "The avengers can be seen fighting aliens from your gorgeous kitchen at this retreat. Beware of aliens.",
    "This home belongs to someone that was snapped away by Thanos. Enjoy your stay!",
    "The owner of this home doesn't know I listed their house for Firebnb. Lol!",
    "If you stay here, you must bring pizza!"
];
function getRandomInRange(from:number, to:number, fixed:number) {
    return Number((Math.random() * (to - from) + from).toFixed(fixed));
}
const generateSpotSeeders = () => {
    let spotArr: Spot[] = [];

    for (let i = 0; i < 18; i++) {
        let spot = {
            userId: 1,
            name: random(propertNames),
            address: fakeAddresses[i],
            city: random(fakeCities),
            state: random(fakeStates),
            country: "United States",
            description: random(fakeDescriptions),
            price: random(20, 200),
            lat: getRandomInRange(-180, 180, 6),
            lng: getRandomInRange(-180, 180, 6),
        };
        spotArr.push(spot);
    }
    return spotArr;
};
export default generateSpotSeeders;
